//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.GameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameEndPoint")]
    public interface IGameEndPoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/SendMessageToRoom", ReplyAction="http://tempuri.org/IGameEndPoint/SendMessageToRoomResponse")]
        void SendMessageToRoom(string roomKey, string message, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/SendMessageToRoom", ReplyAction="http://tempuri.org/IGameEndPoint/SendMessageToRoomResponse")]
        System.Threading.Tasks.Task SendMessageToRoomAsync(string roomKey, string message, string sender);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameEndPointChannel : CatanClient.GameService.IGameEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameEndPointClient : System.ServiceModel.ClientBase<CatanClient.GameService.IGameEndPoint>, CatanClient.GameService.IGameEndPoint {
        
        public GameEndPointClient() {
        }
        
        public GameEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessageToRoom(string roomKey, string message, string sender) {
            base.Channel.SendMessageToRoom(roomKey, message, sender);
        }
        
        public System.Threading.Tasks.Task SendMessageToRoomAsync(string roomKey, string message, string sender) {
            return base.Channel.SendMessageToRoomAsync(roomKey, message, sender);
        }
    }
}
