//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class GameDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAdminGameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxNumberPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessKey {
            get {
                return this.AccessKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessKeyField, value) != true)) {
                    this.AccessKeyField = value;
                    this.RaisePropertyChanged("AccessKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAdminGame {
            get {
                return this.IdAdminGameField;
            }
            set {
                if ((this.IdAdminGameField.Equals(value) != true)) {
                    this.IdAdminGameField = value;
                    this.RaisePropertyChanged("IdAdminGame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxNumberPlayers {
            get {
                return this.MaxNumberPlayersField;
            }
            set {
                if ((this.MaxNumberPlayersField.Equals(value) != true)) {
                    this.MaxNumberPlayersField = value;
                    this.RaisePropertyChanged("MaxNumberPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CurrentSessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRegisteredField;
        
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PictureVersionField;
        
        private string PreferredLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadyToPlayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int votesReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrentSessionID {
            get {
                return this.CurrentSessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentSessionIDField, value) != true)) {
                    this.CurrentSessionIDField = value;
                    this.RaisePropertyChanged("CurrentSessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRegistered {
            get {
                return this.IsRegisteredField;
            }
            set {
                if ((this.IsRegisteredField.Equals(value) != true)) {
                    this.IsRegisteredField = value;
                    this.RaisePropertyChanged("IsRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PictureVersion {
            get {
                return this.PictureVersionField;
            }
            set {
                if ((this.PictureVersionField.Equals(value) != true)) {
                    this.PictureVersionField = value;
                    this.RaisePropertyChanged("PictureVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PreferredLanguage {
            get {
                return this.PreferredLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageField, value) != true)) {
                    this.PreferredLanguageField = value;
                    this.RaisePropertyChanged("PreferredLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isReadyToPlay {
            get {
                return this.isReadyToPlayField;
            }
            set {
                if ((this.isReadyToPlayField.Equals(value) != true)) {
                    this.isReadyToPlayField = value;
                    this.RaisePropertyChanged("isReadyToPlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int votesReceived {
            get {
                return this.votesReceivedField;
            }
            set {
                if ((this.votesReceivedField.Equals(value) != true)) {
                    this.votesReceivedField = value;
                    this.RaisePropertyChanged("votesReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.GameService.OperationResultListOfPlayersInGame))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.GameService.OperationResultListScoreGame))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.GameService.OperationResultGameDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse {
            get {
                return this.MessageResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageResponseField, value) != true)) {
                    this.MessageResponseField = value;
                    this.RaisePropertyChanged("MessageResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultListOfPlayersInGame", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.ResultDto" +
        "s")]
    [System.SerializableAttribute()]
    public partial class OperationResultListOfPlayersInGame : CatanClient.GameService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.GuestAccountDto[] GuestAccountDtosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.ProfileDto[] ProfileDtosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.GuestAccountDto[] GuestAccountDtos {
            get {
                return this.GuestAccountDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestAccountDtosField, value) != true)) {
                    this.GuestAccountDtosField = value;
                    this.RaisePropertyChanged("GuestAccountDtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.ProfileDto[] ProfileDtos {
            get {
                return this.ProfileDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDtosField, value) != true)) {
                    this.ProfileDtosField = value;
                    this.RaisePropertyChanged("ProfileDtos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultListScoreGame", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultListScoreGame : CatanClient.GameService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.ProfileScoreDto[] ListProfileScoreDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.ProfileScoreDto ProfileScoreDtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.ProfileScoreDto[] ListProfileScoreDto {
            get {
                return this.ListProfileScoreDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListProfileScoreDtoField, value) != true)) {
                    this.ListProfileScoreDtoField = value;
                    this.RaisePropertyChanged("ListProfileScoreDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.ProfileScoreDto ProfileScoreDto {
            get {
                return this.ProfileScoreDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileScoreDtoField, value) != true)) {
                    this.ProfileScoreDtoField = value;
                    this.RaisePropertyChanged("ProfileScoreDto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultGameDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultGameDto : CatanClient.GameService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.GameDto GameDtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.GameDto GameDto {
            get {
                return this.GameDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.GameDtoField, value) != true)) {
                    this.GameDtoField = value;
                    this.RaisePropertyChanged("GameDto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestAccountDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class GuestAccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadyToPlayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int votesReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredLanguage {
            get {
                return this.PreferredLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageField, value) != true)) {
                    this.PreferredLanguageField = value;
                    this.RaisePropertyChanged("PreferredLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isReadyToPlay {
            get {
                return this.isReadyToPlayField;
            }
            set {
                if ((this.isReadyToPlayField.Equals(value) != true)) {
                    this.isReadyToPlayField = value;
                    this.RaisePropertyChanged("isReadyToPlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int votesReceived {
            get {
                return this.votesReceivedField;
            }
            set {
                if ((this.votesReceivedField.Equals(value) != true)) {
                    this.votesReceivedField = value;
                    this.RaisePropertyChanged("votesReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileScoreDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProfileScoreDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpelPlayerDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.PlayerDto" +
        "s")]
    [System.SerializableAttribute()]
    public partial class ExpelPlayerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlayerToExpelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlayerToExpel {
            get {
                return this.IdPlayerToExpelField;
            }
            set {
                if ((this.IdPlayerToExpelField.Equals(value) != true)) {
                    this.IdPlayerToExpelField = value;
                    this.RaisePropertyChanged("IdPlayerToExpel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerGameplayDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.PlayerDto" +
        "s")]
    [System.SerializableAttribute()]
    public partial class PlayerGameplayDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentSessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isRegisteredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentSession {
            get {
                return this.CurrentSessionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentSessionField, value) != true)) {
                    this.CurrentSessionField = value;
                    this.RaisePropertyChanged("CurrentSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRegistered {
            get {
                return this.isRegisteredField;
            }
            set {
                if ((this.isRegisteredField.Equals(value) != true)) {
                    this.isRegisteredField = value;
                    this.RaisePropertyChanged("isRegistered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.PlayerDto" +
        "s")]
    [System.SerializableAttribute()]
    public partial class PlayerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.GuestAccountDto guestAccountDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.ProfileDto profileDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.GuestAccountDto guestAccountDto {
            get {
                return this.guestAccountDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.guestAccountDtoField, value) != true)) {
                    this.guestAccountDtoField = value;
                    this.RaisePropertyChanged("guestAccountDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.ProfileDto profileDto {
            get {
                return this.profileDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.profileDtoField, value) != true)) {
                    this.profileDtoField = value;
                    this.RaisePropertyChanged("profileDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerTurnStatusDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.PlayerDto" +
        "s")]
    [System.SerializableAttribute()]
    public partial class PlayerTurnStatusDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.GuestAccountDto GuestAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.ProfileDto ProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.GuestAccountDto GuestAccount {
            get {
                return this.GuestAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestAccountField, value) != true)) {
                    this.GuestAccountField = value;
                    this.RaisePropertyChanged("GuestAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTurn {
            get {
                return this.IsTurnField;
            }
            set {
                if ((this.IsTurnField.Equals(value) != true)) {
                    this.IsTurnField = value;
                    this.RaisePropertyChanged("IsTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.ProfileDto Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameBoardStateDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.GamePlayD" +
        "to")]
    [System.SerializableAttribute()]
    public partial class GameBoardStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.EdgeDto[] EdgesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.HexTileDto[] HexTilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GameService.VertexDto[] VerticesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.EdgeDto[] Edges {
            get {
                return this.EdgesField;
            }
            set {
                if ((object.ReferenceEquals(this.EdgesField, value) != true)) {
                    this.EdgesField = value;
                    this.RaisePropertyChanged("Edges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.HexTileDto[] HexTiles {
            get {
                return this.HexTilesField;
            }
            set {
                if ((object.ReferenceEquals(this.HexTilesField, value) != true)) {
                    this.HexTilesField = value;
                    this.RaisePropertyChanged("HexTiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GameService.VertexDto[] Vertices {
            get {
                return this.VerticesField;
            }
            set {
                if ((object.ReferenceEquals(this.VerticesField, value) != true)) {
                    this.VerticesField = value;
                    this.RaisePropertyChanged("Vertices");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EdgeDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.GamePlayD" +
        "to.Board")]
    [System.SerializableAttribute()]
    public partial class EdgeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ConnectedHexesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOccupiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerPlayerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ConnectedHexes {
            get {
                return this.ConnectedHexesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectedHexesField, value) != true)) {
                    this.ConnectedHexesField = value;
                    this.RaisePropertyChanged("ConnectedHexes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOccupied {
            get {
                return this.IsOccupiedField;
            }
            set {
                if ((this.IsOccupiedField.Equals(value) != true)) {
                    this.IsOccupiedField = value;
                    this.RaisePropertyChanged("IsOccupied");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerPlayerId {
            get {
                return this.OwnerPlayerIdField;
            }
            set {
                if ((this.OwnerPlayerIdField.Equals(value) != true)) {
                    this.OwnerPlayerIdField = value;
                    this.RaisePropertyChanged("OwnerPlayerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HexTileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.GamePlayD" +
        "to.Board")]
    [System.SerializableAttribute()]
    public partial class HexTileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ConnectedVerticesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ConnectedVertices {
            get {
                return this.ConnectedVerticesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectedVerticesField, value) != true)) {
                    this.ConnectedVerticesField = value;
                    this.RaisePropertyChanged("ConnectedVertices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceValue {
            get {
                return this.DiceValueField;
            }
            set {
                if ((this.DiceValueField.Equals(value) != true)) {
                    this.DiceValueField = value;
                    this.RaisePropertyChanged("DiceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resource {
            get {
                return this.ResourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceField, value) != true)) {
                    this.ResourceField = value;
                    this.RaisePropertyChanged("Resource");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VertexDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject.GamePlayD" +
        "to.Board")]
    [System.SerializableAttribute()]
    public partial class VertexDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOccupiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerPlayerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOccupied {
            get {
                return this.IsOccupiedField;
            }
            set {
                if ((this.IsOccupiedField.Equals(value) != true)) {
                    this.IsOccupiedField = value;
                    this.RaisePropertyChanged("IsOccupied");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerPlayerId {
            get {
                return this.OwnerPlayerIdField;
            }
            set {
                if ((this.OwnerPlayerIdField.Equals(value) != true)) {
                    this.OwnerPlayerIdField = value;
                    this.RaisePropertyChanged("OwnerPlayerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameEndPoint", CallbackContract=typeof(CatanClient.GameService.IGameEndPointCallback))]
    public interface IGameEndPoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/CreateGame", ReplyAction="http://tempuri.org/IGameEndPoint/CreateGameResponse")]
        CatanClient.GameService.OperationResultGameDto CreateGame(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/CreateGame", ReplyAction="http://tempuri.org/IGameEndPoint/CreateGameResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> CreateGameAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGame", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGameResponse")]
        CatanClient.GameService.OperationResultDto QuitGame(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGame", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGameResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultDto> QuitGameAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGameAsaGuestAccount", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGameAsaGuestAccountResponse")]
        CatanClient.GameService.OperationResultDto QuitGameAsaGuestAccount(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.GuestAccountDto guestAccountClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGameAsaGuestAccount", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGameAsaGuestAccountResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultDto> QuitGameAsaGuestAccountAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.GuestAccountDto guestAccountClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/JoinGame", ReplyAction="http://tempuri.org/IGameEndPoint/JoinGameResponse")]
        CatanClient.GameService.OperationResultGameDto JoinGame(string codeAccess, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/JoinGame", ReplyAction="http://tempuri.org/IGameEndPoint/JoinGameResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> JoinGameAsync(string codeAccess, CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/JoinGameAsaGuest", ReplyAction="http://tempuri.org/IGameEndPoint/JoinGameAsaGuestResponse")]
        CatanClient.GameService.OperationResultGameDto JoinGameAsaGuest(string accessKey, CatanClient.GameService.GuestAccountDto guestAccountClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/JoinGameAsaGuest", ReplyAction="http://tempuri.org/IGameEndPoint/JoinGameAsaGuestResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> JoinGameAsaGuestAsync(string accessKey, CatanClient.GameService.GuestAccountDto guestAccountClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/ExpelPlayerAsAdmin", ReplyAction="http://tempuri.org/IGameEndPoint/ExpelPlayerAsAdminResponse")]
        bool ExpelPlayerAsAdmin(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idAdmin, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/ExpelPlayerAsAdmin", ReplyAction="http://tempuri.org/IGameEndPoint/ExpelPlayerAsAdminResponse")]
        System.Threading.Tasks.Task<bool> ExpelPlayerAsAdminAsync(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idAdmin, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/VoteExpelPlayer", ReplyAction="http://tempuri.org/IGameEndPoint/VoteExpelPlayerResponse")]
        bool VoteExpelPlayer(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idPlayer, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/VoteExpelPlayer", ReplyAction="http://tempuri.org/IGameEndPoint/VoteExpelPlayerResponse")]
        System.Threading.Tasks.Task<bool> VoteExpelPlayerAsync(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idPlayer, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetAllPlayersInGame", ReplyAction="http://tempuri.org/IGameEndPoint/GetAllPlayersInGameResponse")]
        CatanClient.GameService.OperationResultListOfPlayersInGame GetAllPlayersInGame(CatanClient.GameService.GameDto gameClientDto, string preferredLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetAllPlayersInGame", ReplyAction="http://tempuri.org/IGameEndPoint/GetAllPlayersInGameResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListOfPlayersInGame> GetAllPlayersInGameAsync(CatanClient.GameService.GameDto gameClientDto, string preferredLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetScoreGameWorld", ReplyAction="http://tempuri.org/IGameEndPoint/GetScoreGameWorldResponse")]
        CatanClient.GameService.OperationResultListScoreGame GetScoreGameWorld(CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetScoreGameWorld", ReplyAction="http://tempuri.org/IGameEndPoint/GetScoreGameWorldResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListScoreGame> GetScoreGameWorldAsync(CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetScoreGameFriends", ReplyAction="http://tempuri.org/IGameEndPoint/GetScoreGameFriendsResponse")]
        CatanClient.GameService.OperationResultListScoreGame GetScoreGameFriends(CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/GetScoreGameFriends", ReplyAction="http://tempuri.org/IGameEndPoint/GetScoreGameFriendsResponse")]
        System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListScoreGame> GetScoreGameFriendsAsync(CatanClient.GameService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/StartGame", ReplyAction="http://tempuri.org/IGameEndPoint/StartGameResponse")]
        bool StartGame(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/StartGame", ReplyAction="http://tempuri.org/IGameEndPoint/StartGameResponse")]
        System.Threading.Tasks.Task<bool> StartGameAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/NextTurnAync", ReplyAction="http://tempuri.org/IGameEndPoint/NextTurnAyncResponse")]
        bool NextTurnAync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/NextTurnAync", ReplyAction="http://tempuri.org/IGameEndPoint/NextTurnAyncResponse")]
        System.Threading.Tasks.Task<bool> NextTurnAyncAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/ThrowDice", ReplyAction="http://tempuri.org/IGameEndPoint/ThrowDiceResponse")]
        void ThrowDice(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto, int valueDice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/ThrowDice", ReplyAction="http://tempuri.org/IGameEndPoint/ThrowDiceResponse")]
        System.Threading.Tasks.Task ThrowDiceAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto, int valueDice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGamePlay", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGamePlayResponse")]
        void QuitGamePlay(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameEndPoint/QuitGamePlay", ReplyAction="http://tempuri.org/IGameEndPoint/QuitGamePlayResponse")]
        System.Threading.Tasks.Task QuitGamePlayAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameEndPointCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/NotifyPlayerExpulsion")]
        void NotifyPlayerExpulsion(string message, string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/BroadcastMessageExpel")]
        void BroadcastMessageExpel(CatanClient.GameService.PlayerDto playerExpeled);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/BroadcastNotifyNewAdmin")]
        void BroadcastNotifyNewAdmin(int idAdmin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/UpdateTimeToStartGame")]
        void UpdateTimeToStartGame(int time);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/UpdateTimeWhenJoinGame")]
        void UpdateTimeWhenJoinGame(int time);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/StartGameForAllPlayers")]
        void StartGameForAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/UpdateTurnStatus")]
        void UpdateTurnStatus(CatanClient.GameService.PlayerTurnStatusDto[] playersTurnStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/UpdateTurnTimeRemaining")]
        void UpdateTurnTimeRemaining(int remainingTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/SendDiceResult")]
        void SendDiceResult(int diceResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/SendUpdateConnectedPlayers")]
        void SendUpdateConnectedPlayers(CatanClient.GameService.OperationResultListOfPlayersInGame listOfPlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/EndGameDisconnectedPlayers")]
        void EndGameDisconnectedPlayers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/UpdateListOfPlayersTurns")]
        void UpdateListOfPlayersTurns(CatanClient.GameService.PlayerTurnStatusDto[] playersTurnStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameEndPoint/NotifyGameBoardInitialized")]
        void NotifyGameBoardInitialized(CatanClient.GameService.GameBoardStateDto gameBoardState);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameEndPointChannel : CatanClient.GameService.IGameEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameEndPointClient : System.ServiceModel.DuplexClientBase<CatanClient.GameService.IGameEndPoint>, CatanClient.GameService.IGameEndPoint {
        
        public GameEndPointClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameEndPointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameEndPointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameEndPointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameEndPointClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CatanClient.GameService.OperationResultGameDto CreateGame(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.CreateGame(gameClientDto, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> CreateGameAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.CreateGameAsync(gameClientDto, profileClientDto);
        }
        
        public CatanClient.GameService.OperationResultDto QuitGame(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.QuitGame(gameClientDto, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultDto> QuitGameAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.QuitGameAsync(gameClientDto, profileClientDto);
        }
        
        public CatanClient.GameService.OperationResultDto QuitGameAsaGuestAccount(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.GuestAccountDto guestAccountClientDto) {
            return base.Channel.QuitGameAsaGuestAccount(gameClientDto, guestAccountClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultDto> QuitGameAsaGuestAccountAsync(CatanClient.GameService.GameDto gameClientDto, CatanClient.GameService.GuestAccountDto guestAccountClientDto) {
            return base.Channel.QuitGameAsaGuestAccountAsync(gameClientDto, guestAccountClientDto);
        }
        
        public CatanClient.GameService.OperationResultGameDto JoinGame(string codeAccess, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.JoinGame(codeAccess, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> JoinGameAsync(string codeAccess, CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.JoinGameAsync(codeAccess, profileClientDto);
        }
        
        public CatanClient.GameService.OperationResultGameDto JoinGameAsaGuest(string accessKey, CatanClient.GameService.GuestAccountDto guestAccountClientDto) {
            return base.Channel.JoinGameAsaGuest(accessKey, guestAccountClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultGameDto> JoinGameAsaGuestAsync(string accessKey, CatanClient.GameService.GuestAccountDto guestAccountClientDto) {
            return base.Channel.JoinGameAsaGuestAsync(accessKey, guestAccountClientDto);
        }
        
        public bool ExpelPlayerAsAdmin(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idAdmin, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.ExpelPlayerAsAdmin(expelPlayerDto, idAdmin, gameClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> ExpelPlayerAsAdminAsync(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idAdmin, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.ExpelPlayerAsAdminAsync(expelPlayerDto, idAdmin, gameClientDto);
        }
        
        public bool VoteExpelPlayer(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idPlayer, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.VoteExpelPlayer(expelPlayerDto, idPlayer, gameClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> VoteExpelPlayerAsync(CatanClient.GameService.ExpelPlayerDto expelPlayerDto, int idPlayer, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.VoteExpelPlayerAsync(expelPlayerDto, idPlayer, gameClientDto);
        }
        
        public CatanClient.GameService.OperationResultListOfPlayersInGame GetAllPlayersInGame(CatanClient.GameService.GameDto gameClientDto, string preferredLanguage) {
            return base.Channel.GetAllPlayersInGame(gameClientDto, preferredLanguage);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListOfPlayersInGame> GetAllPlayersInGameAsync(CatanClient.GameService.GameDto gameClientDto, string preferredLanguage) {
            return base.Channel.GetAllPlayersInGameAsync(gameClientDto, preferredLanguage);
        }
        
        public CatanClient.GameService.OperationResultListScoreGame GetScoreGameWorld(CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.GetScoreGameWorld(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListScoreGame> GetScoreGameWorldAsync(CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.GetScoreGameWorldAsync(profileClientDto);
        }
        
        public CatanClient.GameService.OperationResultListScoreGame GetScoreGameFriends(CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.GetScoreGameFriends(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GameService.OperationResultListScoreGame> GetScoreGameFriendsAsync(CatanClient.GameService.ProfileDto profileClientDto) {
            return base.Channel.GetScoreGameFriendsAsync(profileClientDto);
        }
        
        public bool StartGame(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.StartGame(playerGameplayDto, gameClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> StartGameAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.StartGameAsync(playerGameplayDto, gameClientDto);
        }
        
        public bool NextTurnAync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.NextTurnAync(playerGameplayDto, gameClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> NextTurnAyncAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.NextTurnAyncAsync(playerGameplayDto, gameClientDto);
        }
        
        public void ThrowDice(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto, int valueDice) {
            base.Channel.ThrowDice(playerGameplayDto, gameClientDto, valueDice);
        }
        
        public System.Threading.Tasks.Task ThrowDiceAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto, int valueDice) {
            return base.Channel.ThrowDiceAsync(playerGameplayDto, gameClientDto, valueDice);
        }
        
        public void QuitGamePlay(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            base.Channel.QuitGamePlay(playerGameplayDto, gameClientDto);
        }
        
        public System.Threading.Tasks.Task QuitGamePlayAsync(CatanClient.GameService.PlayerGameplayDto playerGameplayDto, CatanClient.GameService.GameDto gameClientDto) {
            return base.Channel.QuitGamePlayAsync(playerGameplayDto, gameClientDto);
        }
    }
}
