//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CurrentSessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRegisteredField;
        
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PictureVersionField;
        
        private string PreferredLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadyToPlayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrentSessionID {
            get {
                return this.CurrentSessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentSessionIDField, value) != true)) {
                    this.CurrentSessionIDField = value;
                    this.RaisePropertyChanged("CurrentSessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRegistered {
            get {
                return this.IsRegisteredField;
            }
            set {
                if ((this.IsRegisteredField.Equals(value) != true)) {
                    this.IsRegisteredField = value;
                    this.RaisePropertyChanged("IsRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PictureVersion {
            get {
                return this.PictureVersionField;
            }
            set {
                if ((this.PictureVersionField.Equals(value) != true)) {
                    this.PictureVersionField = value;
                    this.RaisePropertyChanged("PictureVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PreferredLanguage {
            get {
                return this.PreferredLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageField, value) != true)) {
                    this.PreferredLanguageField = value;
                    this.RaisePropertyChanged("PreferredLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isReadyToPlay {
            get {
                return this.isReadyToPlayField;
            }
            set {
                if ((this.isReadyToPlayField.Equals(value) != true)) {
                    this.isReadyToPlayField = value;
                    this.RaisePropertyChanged("isReadyToPlay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.ProfileService.OperationResultPictureDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.ProfileService.OperationResultProfileListDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.ProfileService.OperationResultProfileDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse {
            get {
                return this.MessageResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageResponseField, value) != true)) {
                    this.MessageResponseField = value;
                    this.RaisePropertyChanged("MessageResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultPictureDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultPictureDto : CatanClient.ProfileService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultProfileListDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultProfileListDto : CatanClient.ProfileService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.ProfileDto[] ProfileDtosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.ProfileDto[] ProfileDtos {
            get {
                return this.ProfileDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDtosField, value) != true)) {
                    this.ProfileDtosField = value;
                    this.RaisePropertyChanged("ProfileDtos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultProfileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultProfileDto : CatanClient.ProfileService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.EnumAuthenticationStatus AunthenticationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.EnumChangeAccountRegister ChangeAccountRegisterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.ProfileDto ProfileDtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.EnumAuthenticationStatus AunthenticationStatus {
            get {
                return this.AunthenticationStatusField;
            }
            set {
                if ((this.AunthenticationStatusField.Equals(value) != true)) {
                    this.AunthenticationStatusField = value;
                    this.RaisePropertyChanged("AunthenticationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.EnumChangeAccountRegister ChangeAccountRegister {
            get {
                return this.ChangeAccountRegisterField;
            }
            set {
                if ((this.ChangeAccountRegisterField.Equals(value) != true)) {
                    this.ChangeAccountRegisterField = value;
                    this.RaisePropertyChanged("ChangeAccountRegister");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.ProfileDto ProfileDto {
            get {
                return this.ProfileDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDtoField, value) != true)) {
                    this.ProfileDtoField = value;
                    this.RaisePropertyChanged("ProfileDto");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumAuthenticationStatus", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject.Enums")]
    public enum EnumAuthenticationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incorrect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotVerified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerNotFound = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumChangeAccountRegister", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject.Enums")]
    public enum EnumChangeAccountRegister : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToSaveData = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IProfileServiceEndpoint")]
    public interface IProfileServiceEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileName", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileNameResponse")]
        CatanClient.ProfileService.OperationResultProfileDto ChangeProfileName(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileName", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileNameResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> ChangeProfileNameAsync(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/UploadProfilePicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/UploadProfilePictureResponse")]
        CatanClient.ProfileService.OperationResultProfileDto UploadProfilePicture(CatanClient.ProfileService.ProfileDto profileClientDto, byte[] imageInBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/UploadProfilePicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/UploadProfilePictureResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> UploadProfilePictureAsync(CatanClient.ProfileService.ProfileDto profileClientDto, byte[] imageInBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetProfilePicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetProfilePictureResponse")]
        CatanClient.ProfileService.OperationResultPictureDto GetProfilePicture(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetProfilePicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetProfilePictureResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultPictureDto> GetProfilePictureAsync(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetFriendsPicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetFriendsPictureResponse")]
        CatanClient.ProfileService.OperationResultPictureDto GetFriendsPicture(CatanClient.ProfileService.ProfileDto profileFriendDto, string PreferredLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetFriendsPicture", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetFriendsPictureResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultPictureDto> GetFriendsPictureAsync(CatanClient.ProfileService.ProfileDto profileFriendDto, string PreferredLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/InviteFriendsToGame", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/InviteFriendsToGameResponse")]
        bool InviteFriendsToGame(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/InviteFriendsToGame", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/InviteFriendsToGameResponse")]
        System.Threading.Tasks.Task<bool> InviteFriendsToGameAsync(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetFriendsList", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetFriendsListResponse")]
        CatanClient.ProfileService.OperationResultProfileListDto GetFriendsList(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetFriendsList", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetFriendsListResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileListDto> GetFriendsListAsync(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetPendingFriendRequests", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetPendingFriendRequestsResponse")]
        CatanClient.ProfileService.OperationResultProfileListDto GetPendingFriendRequests(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/GetPendingFriendRequests", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/GetPendingFriendRequestsResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileListDto> GetPendingFriendRequestsAsync(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/SendFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/SendFriendRequestResponse")]
        bool SendFriendRequest(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/SendFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/AcceptFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/AcceptFriendRequestResponse")]
        bool AcceptFriendRequest(string nameFriendToAccept, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/AcceptFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string nameFriendToAccept, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/RejectFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/RejectFriendRequestResponse")]
        bool RejectFriendRequest(string nameFriendToReject, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/RejectFriendRequest", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/RejectFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> RejectFriendRequestAsync(string nameFriendToReject, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/DeleteFriendProfile", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/DeleteFriendProfileResponse")]
        bool DeleteFriendProfile(string friendName, CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/DeleteFriendProfile", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/DeleteFriendProfileResponse")]
        System.Threading.Tasks.Task<bool> DeleteFriendProfileAsync(string friendName, CatanClient.ProfileService.ProfileDto profileClientDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceEndpointChannel : CatanClient.ProfileService.IProfileServiceEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceEndpointClient : System.ServiceModel.ClientBase<CatanClient.ProfileService.IProfileServiceEndpoint>, CatanClient.ProfileService.IProfileServiceEndpoint {
        
        public ProfileServiceEndpointClient() {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CatanClient.ProfileService.OperationResultProfileDto ChangeProfileName(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.ChangeProfileName(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> ChangeProfileNameAsync(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.ChangeProfileNameAsync(profileClientDto);
        }
        
        public CatanClient.ProfileService.OperationResultProfileDto UploadProfilePicture(CatanClient.ProfileService.ProfileDto profileClientDto, byte[] imageInBytes) {
            return base.Channel.UploadProfilePicture(profileClientDto, imageInBytes);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> UploadProfilePictureAsync(CatanClient.ProfileService.ProfileDto profileClientDto, byte[] imageInBytes) {
            return base.Channel.UploadProfilePictureAsync(profileClientDto, imageInBytes);
        }
        
        public CatanClient.ProfileService.OperationResultPictureDto GetProfilePicture(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetProfilePicture(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultPictureDto> GetProfilePictureAsync(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetProfilePictureAsync(profileClientDto);
        }
        
        public CatanClient.ProfileService.OperationResultPictureDto GetFriendsPicture(CatanClient.ProfileService.ProfileDto profileFriendDto, string PreferredLanguage) {
            return base.Channel.GetFriendsPicture(profileFriendDto, PreferredLanguage);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultPictureDto> GetFriendsPictureAsync(CatanClient.ProfileService.ProfileDto profileFriendDto, string PreferredLanguage) {
            return base.Channel.GetFriendsPictureAsync(profileFriendDto, PreferredLanguage);
        }
        
        public bool InviteFriendsToGame(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto, string accessKey) {
            return base.Channel.InviteFriendsToGame(nameFriendToInvite, profileClientDto, accessKey);
        }
        
        public System.Threading.Tasks.Task<bool> InviteFriendsToGameAsync(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto, string accessKey) {
            return base.Channel.InviteFriendsToGameAsync(nameFriendToInvite, profileClientDto, accessKey);
        }
        
        public CatanClient.ProfileService.OperationResultProfileListDto GetFriendsList(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetFriendsList(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileListDto> GetFriendsListAsync(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetFriendsListAsync(profileClientDto);
        }
        
        public CatanClient.ProfileService.OperationResultProfileListDto GetPendingFriendRequests(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetPendingFriendRequests(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileListDto> GetPendingFriendRequestsAsync(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.GetPendingFriendRequestsAsync(profileClientDto);
        }
        
        public bool SendFriendRequest(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.SendFriendRequest(nameFriendToInvite, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string nameFriendToInvite, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.SendFriendRequestAsync(nameFriendToInvite, profileClientDto);
        }
        
        public bool AcceptFriendRequest(string nameFriendToAccept, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.AcceptFriendRequest(nameFriendToAccept, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string nameFriendToAccept, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.AcceptFriendRequestAsync(nameFriendToAccept, profileClientDto);
        }
        
        public bool RejectFriendRequest(string nameFriendToReject, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.RejectFriendRequest(nameFriendToReject, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> RejectFriendRequestAsync(string nameFriendToReject, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.RejectFriendRequestAsync(nameFriendToReject, profileClientDto);
        }
        
        public bool DeleteFriendProfile(string friendName, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.DeleteFriendProfile(friendName, profileClientDto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFriendProfileAsync(string friendName, CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.DeleteFriendProfileAsync(friendName, profileClientDto);
        }
    }
}
