//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicturePathField;
        
        private string PreferredLanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicturePath {
            get {
                return this.PicturePathField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturePathField, value) != true)) {
                    this.PicturePathField = value;
                    this.RaisePropertyChanged("PicturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PreferredLanguage {
            get {
                return this.PreferredLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageField, value) != true)) {
                    this.PreferredLanguageField = value;
                    this.RaisePropertyChanged("PreferredLanguage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.ProfileService.OperationResultProfileDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse {
            get {
                return this.MessageResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageResponseField, value) != true)) {
                    this.MessageResponseField = value;
                    this.RaisePropertyChanged("MessageResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultProfileDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultProfileDto : CatanClient.ProfileService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.EnumAuthenticationStatus AunthenticationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.EnumChangeAccountRegister ChangeAccountRegisterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.ProfileService.ProfileDto ProfileDtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.EnumAuthenticationStatus AunthenticationStatus {
            get {
                return this.AunthenticationStatusField;
            }
            set {
                if ((this.AunthenticationStatusField.Equals(value) != true)) {
                    this.AunthenticationStatusField = value;
                    this.RaisePropertyChanged("AunthenticationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.EnumChangeAccountRegister ChangeAccountRegister {
            get {
                return this.ChangeAccountRegisterField;
            }
            set {
                if ((this.ChangeAccountRegisterField.Equals(value) != true)) {
                    this.ChangeAccountRegisterField = value;
                    this.RaisePropertyChanged("ChangeAccountRegister");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.ProfileService.ProfileDto ProfileDto {
            get {
                return this.ProfileDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDtoField, value) != true)) {
                    this.ProfileDtoField = value;
                    this.RaisePropertyChanged("ProfileDto");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumAuthenticationStatus", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject.Enums")]
    public enum EnumAuthenticationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incorrect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotVerified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerNotFound = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumChangeAccountRegister", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject.Enums")]
    public enum EnumChangeAccountRegister : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToSaveData = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IProfileServiceEndpoint")]
    public interface IProfileServiceEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileName", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileNameResponse")]
        CatanClient.ProfileService.OperationResultProfileDto ChangeProfileName(CatanClient.ProfileService.ProfileDto profileClientDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileName", ReplyAction="http://tempuri.org/IProfileServiceEndpoint/ChangeProfileNameResponse")]
        System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> ChangeProfileNameAsync(CatanClient.ProfileService.ProfileDto profileClientDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceEndpointChannel : CatanClient.ProfileService.IProfileServiceEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceEndpointClient : System.ServiceModel.ClientBase<CatanClient.ProfileService.IProfileServiceEndpoint>, CatanClient.ProfileService.IProfileServiceEndpoint {
        
        public ProfileServiceEndpointClient() {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CatanClient.ProfileService.OperationResultProfileDto ChangeProfileName(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.ChangeProfileName(profileClientDto);
        }
        
        public System.Threading.Tasks.Task<CatanClient.ProfileService.OperationResultProfileDto> ChangeProfileNameAsync(CatanClient.ProfileService.ProfileDto profileClientDto) {
            return base.Channel.ChangeProfileNameAsync(profileClientDto);
        }
    }
}
