//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.GuestAccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatanClient.GuestAccountService.OperationResultGuestAccountDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse {
            get {
                return this.MessageResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageResponseField, value) != true)) {
                    this.MessageResponseField = value;
                    this.RaisePropertyChanged("MessageResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultGuestAccountDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class OperationResultGuestAccountDto : CatanClient.GuestAccountService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CatanClient.GuestAccountService.GuestAccountDto GuestAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatanClient.GuestAccountService.GuestAccountDto GuestAccount {
            get {
                return this.GuestAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestAccountField, value) != true)) {
                    this.GuestAccountField = value;
                    this.RaisePropertyChanged("GuestAccount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestAccountDto", Namespace="http://schemas.datacontract.org/2004/07/CatanService.DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class GuestAccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadyToPlayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int votesReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredLanguage {
            get {
                return this.PreferredLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageField, value) != true)) {
                    this.PreferredLanguageField = value;
                    this.RaisePropertyChanged("PreferredLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isReadyToPlay {
            get {
                return this.isReadyToPlayField;
            }
            set {
                if ((this.isReadyToPlayField.Equals(value) != true)) {
                    this.isReadyToPlayField = value;
                    this.RaisePropertyChanged("isReadyToPlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int votesReceived {
            get {
                return this.votesReceivedField;
            }
            set {
                if ((this.votesReceivedField.Equals(value) != true)) {
                    this.votesReceivedField = value;
                    this.RaisePropertyChanged("votesReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestAccountService.IGuestAccountEndpoint")]
    public interface IGuestAccountEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestAccountEndpoint/CreateGuestAccount", ReplyAction="http://tempuri.org/IGuestAccountEndpoint/CreateGuestAccountResponse")]
        CatanClient.GuestAccountService.OperationResultGuestAccountDto CreateGuestAccount(string preferredLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestAccountEndpoint/CreateGuestAccount", ReplyAction="http://tempuri.org/IGuestAccountEndpoint/CreateGuestAccountResponse")]
        System.Threading.Tasks.Task<CatanClient.GuestAccountService.OperationResultGuestAccountDto> CreateGuestAccountAsync(string preferredLanguage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestAccountEndpointChannel : CatanClient.GuestAccountService.IGuestAccountEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestAccountEndpointClient : System.ServiceModel.ClientBase<CatanClient.GuestAccountService.IGuestAccountEndpoint>, CatanClient.GuestAccountService.IGuestAccountEndpoint {
        
        public GuestAccountEndpointClient() {
        }
        
        public GuestAccountEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestAccountEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestAccountEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestAccountEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CatanClient.GuestAccountService.OperationResultGuestAccountDto CreateGuestAccount(string preferredLanguage) {
            return base.Channel.CreateGuestAccount(preferredLanguage);
        }
        
        public System.Threading.Tasks.Task<CatanClient.GuestAccountService.OperationResultGuestAccountDto> CreateGuestAccountAsync(string preferredLanguage) {
            return base.Channel.CreateGuestAccountAsync(preferredLanguage);
        }
    }
}
