//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatanClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abort.
        /// </summary>
        public static string button_abort {
            get {
                return ResourceManager.GetString("button_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string button_accept {
            get {
                return ResourceManager.GetString("button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string button_close {
            get {
                return ResourceManager.GetString("button_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string button_confirm {
            get {
                return ResourceManager.GetString("button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string button_continue {
            get {
                return ResourceManager.GetString("button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string button_create_game {
            get {
                return ResourceManager.GetString("button_create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string button_decline {
            get {
                return ResourceManager.GetString("button_decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need help?.
        /// </summary>
        public static string button_help {
            get {
                return ResourceManager.GetString("button_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string button_invite {
            get {
                return ResourceManager.GetString("button_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string button_join_game {
            get {
                return ResourceManager.GetString("button_join_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Room!.
        /// </summary>
        public static string button_join_room {
            get {
                return ResourceManager.GetString("button_join_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string button_log_out {
            get {
                return ResourceManager.GetString("button_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string button_modify {
            get {
                return ResourceManager.GetString("button_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as a gest.
        /// </summary>
        public static string button_play_as_gest {
            get {
                return ResourceManager.GetString("button_play_as_gest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string button_ready {
            get {
                return ResourceManager.GetString("button_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend.
        /// </summary>
        public static string button_resend {
            get {
                return ResourceManager.GetString("button_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Photo.
        /// </summary>
        public static string button_save_photo {
            get {
                return ResourceManager.GetString("button_save_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboard.
        /// </summary>
        public static string button_scoreboard {
            get {
                return ResourceManager.GetString("button_scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string button_send {
            get {
                return ResourceManager.GetString("button_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Profile.
        /// </summary>
        public static string button_view_profile {
            get {
                return ResourceManager.GetString("button_view_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Password.
        /// </summary>
        public static string check_box_show_password {
            get {
                return ResourceManager.GetString("check_box_show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is already in use.
        /// </summary>
        public static string dialog_account_in_use {
            get {
                return ResourceManager.GetString("dialog_account_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the name of the player you wish to add as a friend.
        /// </summary>
        public static string dialog_add_new_friend {
            get {
                return ResourceManager.GetString("dialog_add_new_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construction.
        /// </summary>
        public static string dialog_build {
            get {
                return ResourceManager.GetString("dialog_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the password change?.
        /// </summary>
        public static string dialog_cancel_change_password_message {
            get {
                return ResourceManager.GetString("dialog_cancel_change_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change username.
        /// </summary>
        public static string dialog_change_username {
            get {
                return ResourceManager.GetString("dialog_change_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to change username.
        /// </summary>
        public static string dialog_change_username_fail_message {
            get {
                return ResourceManager.GetString("dialog_change_username_fail_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username has been changed successfully.
        /// </summary>
        public static string dialog_change_username_succes_message {
            get {
                return ResourceManager.GetString("dialog_change_username_succes_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A message with a code has been sent to your email or phone number. Please enter the code to save the changes..
        /// </summary>
        public static string dialog_code_sent_message {
            get {
                return ResourceManager.GetString("dialog_code_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this user from your friends list?.
        /// </summary>
        public static string dialog_confirm_remove_friend_message {
            get {
                return ResourceManager.GetString("dialog_confirm_remove_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to vote to expel the player?.
        /// </summary>
        public static string dialog_confirm_vote_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_confirm_vote_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection was lost..
        /// </summary>
        public static string dialog_connection_server_exception {
            get {
                return ResourceManager.GetString("dialog_connection_server_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection was lost, please try again later.
        /// </summary>
        public static string dialog_connection_server_exception_message {
            get {
                return ResourceManager.GetString("dialog_connection_server_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to load data..
        /// </summary>
        public static string dialog_database_load_exception {
            get {
                return ResourceManager.GetString("dialog_database_load_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to save data.
        /// </summary>
        public static string dialog_database_load_exception_message {
            get {
                return ResourceManager.GetString("dialog_database_load_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to save data.
        /// </summary>
        public static string dialog_database_save_exception {
            get {
                return ResourceManager.GetString("dialog_database_save_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving the data, please try again.
        /// </summary>
        public static string dialog_database_save_exception_message {
            get {
                return ResourceManager.GetString("dialog_database_save_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty fields.
        /// </summary>
        public static string dialog_empty_fields {
            get {
                return ResourceManager.GetString("dialog_empty_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required fields have been left empty.
        /// </summary>
        public static string dialog_empty_fields_message {
            get {
                return ResourceManager.GetString("dialog_empty_fields_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The necessary resources are not available to complete this exchange..
        /// </summary>
        public static string dialog_error_trading_message {
            get {
                return ResourceManager.GetString("dialog_error_trading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid characters.
        /// </summary>
        public static string dialog_exception_service {
            get {
                return ResourceManager.GetString("dialog_exception_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fail.
        /// </summary>
        public static string dialog_fail {
            get {
                return ResourceManager.GetString("dialog_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User verification failed, the verification code is incorrect.
        /// </summary>
        public static string dialog_fail_verify_user_message {
            get {
                return ResourceManager.GetString("dialog_fail_verify_user_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This player has been added to your friends list.
        /// </summary>
        public static string dialog_friend_added_message {
            get {
                return ResourceManager.GetString("dialog_friend_added_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to join the room, the maximum number of members has been reached..
        /// </summary>
        public static string dialog_full_game_message {
            get {
                return ResourceManager.GetString("dialog_full_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No players left, the game has ended.
        /// </summary>
        public static string dialog_game_end_no_players_message {
            get {
                return ResourceManager.GetString("dialog_game_end_no_players_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Over.
        /// </summary>
        public static string dialog_game_end_title {
            get {
                return ResourceManager.GetString("dialog_game_end_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been expelled from the game.
        /// </summary>
        public static string dialog_game_expel_message {
            get {
                return ResourceManager.GetString("dialog_game_expel_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room was not found..
        /// </summary>
        public static string dialog_game_not_found_message {
            get {
                return ResourceManager.GetString("dialog_game_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect code. Please check that it is entered correctly and try again.
        /// </summary>
        public static string dialog_incorrect_code_message {
            get {
                return ResourceManager.GetString("dialog_incorrect_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid characters have been entered.
        /// </summary>
        public static string dialog_invalid_characters_message {
            get {
                return ResourceManager.GetString("dialog_invalid_characters_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid characters have been entered, please include only numbers, letters, and the symbols &apos;.&apos;, &apos;-&apos;, and &apos;_&apos;..
        /// </summary>
        public static string dialog_invalid_password_characters {
            get {
                return ResourceManager.GetString("dialog_invalid_password_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid characters have been entered, please include only numbers and letters.
        /// </summary>
        public static string dialog_invalid_username_characters {
            get {
                return ResourceManager.GetString("dialog_invalid_username_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect username or password.
        /// </summary>
        public static string dialog_invalid_username_password {
            get {
                return ResourceManager.GetString("dialog_invalid_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An incorrect username or password has been entered.
        /// </summary>
        public static string dialog_invalid_username_password_message {
            get {
                return ResourceManager.GetString("dialog_invalid_username_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend has been successfully invited to the game.
        /// </summary>
        public static string dialog_invitation_message {
            get {
                return ResourceManager.GetString("dialog_invitation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to kick the player?.
        /// </summary>
        public static string dialog_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked from the room for reason:.
        /// </summary>
        public static string dialog_kicked_player_message {
            get {
                return ResourceManager.GetString("dialog_kicked_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This name is already in use.
        /// </summary>
        public static string dialog_name_in_use {
            get {
                return ResourceManager.GetString("dialog_name_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That name was not found registered as an account, please check it and try again.
        /// </summary>
        public static string dialog_name_not_found_message {
            get {
                return ResourceManager.GetString("dialog_name_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No friend requests have been received yet.
        /// </summary>
        public static string dialog_not_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_not_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated successfully.
        /// </summary>
        public static string dialog_password_changed {
            get {
                return ResourceManager.GetString("dialog_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password has been changed successfully.
        /// </summary>
        public static string dialog_password_changed_message {
            get {
                return ResourceManager.GetString("dialog_password_changed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string dialog_password_dont_match_message {
            get {
                return ResourceManager.GetString("dialog_password_dont_match_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords do not match.
        /// </summary>
        public static string dialog_password_not_match {
            get {
                return ResourceManager.GetString("dialog_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration has been cancelled..
        /// </summary>
        public static string dialog_registration_cancelled_message {
            get {
                return ResourceManager.GetString("dialog_registration_cancelled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request has been rejected.
        /// </summary>
        public static string dialog_reject_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_reject_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove friend.
        /// </summary>
        public static string dialog_remove_friend {
            get {
                return ResourceManager.GetString("dialog_remove_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resent code.
        /// </summary>
        public static string dialog_resent_code {
            get {
                return ResourceManager.GetString("dialog_resent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code has been resent..
        /// </summary>
        public static string dialog_resent_code_message {
            get {
                return ResourceManager.GetString("dialog_resent_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game will restart.
        /// </summary>
        public static string dialog_restart_message {
            get {
                return ResourceManager.GetString("dialog_restart_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request has been sent successfully.
        /// </summary>
        public static string dialog_send_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_send_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Succes.
        /// </summary>
        public static string dialog_succes {
            get {
                return ResourceManager.GetString("dialog_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player has been successfully added as a friend:.
        /// </summary>
        public static string dialog_succes_add_friend_message {
            get {
                return ResourceManager.GetString("dialog_succes_add_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request has been sent.
        /// </summary>
        public static string dialog_succes_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_succes_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player has been successfully kicked.
        /// </summary>
        public static string dialog_succes_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_succes_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player has been rejected as a friend:.
        /// </summary>
        public static string dialog_succes_reject_friend_message {
            get {
                return ResourceManager.GetString("dialog_succes_reject_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend has been removed successfully.
        /// </summary>
        public static string dialog_succes_remove_friend_message {
            get {
                return ResourceManager.GetString("dialog_succes_remove_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification code has been sent to your email or phone.
        /// </summary>
        public static string dialog_succes_send_code_message {
            get {
                return ResourceManager.GetString("dialog_succes_send_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The trade offer has been sent.
        /// </summary>
        public static string dialog_succes_send_trade_message {
            get {
                return ResourceManager.GetString("dialog_succes_send_trade_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The trade has been successfully completed.
        /// </summary>
        public static string dialog_succes_trade_message {
            get {
                return ResourceManager.GetString("dialog_succes_trade_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User verified successfully.
        /// </summary>
        public static string dialog_succes_verify_user_message {
            get {
                return ResourceManager.GetString("dialog_succes_verify_user_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string dialog_success {
            get {
                return ResourceManager.GetString("dialog_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The construction was successfully placed..
        /// </summary>
        public static string dialog_successful_build_message {
            get {
                return ResourceManager.GetString("dialog_successful_build_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file is too large. The maximum size is 6 MB..
        /// </summary>
        public static string dialog_too_big_file_message {
            get {
                return ResourceManager.GetString("dialog_too_big_file_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unregistered email.
        /// </summary>
        public static string dialog_unregistered_email {
            get {
                return ResourceManager.GetString("dialog_unregistered_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email you entered is not registered..
        /// </summary>
        public static string dialog_unregistered_email_message {
            get {
                return ResourceManager.GetString("dialog_unregistered_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot place the construction here..
        /// </summary>
        public static string dialog_unsuccessful_build_message {
            get {
                return ResourceManager.GetString("dialog_unsuccessful_build_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unverified user.
        /// </summary>
        public static string dialog_unverified_user {
            get {
                return ResourceManager.GetString("dialog_unverified_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user is not verified, please verify.
        /// </summary>
        public static string dialog_unverified_user_message {
            get {
                return ResourceManager.GetString("dialog_unverified_user_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification code has been sent to your email or phone number. Please confirm your account by entering the access code..
        /// </summary>
        public static string dialog_verification_account_message {
            get {
                return ResourceManager.GetString("dialog_verification_account_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify account.
        /// </summary>
        public static string dialog_verify_account {
            get {
                return ResourceManager.GetString("dialog_verify_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your vote to expel the player has been registered.
        /// </summary>
        public static string dialog_vote_registered_message {
            get {
                return ResourceManager.GetString("dialog_vote_registered_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, User.
        /// </summary>
        public static string dialog_welcome {
            get {
                return ResourceManager.GetString("dialog_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked out of the game..
        /// </summary>
        public static string dialog_you_have_been_kicked_message {
            get {
                return ResourceManager.GetString("dialog_you_have_been_kicked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example: user@domain.com.
        /// </summary>
        public static string email_prompt {
            get {
                return ResourceManager.GetString("email_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game has started.
        /// </summary>
        public static string game_started {
            get {
                return ResourceManager.GetString("game_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string global_add_friend {
            get {
                return ResourceManager.GetString("global_add_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel change.
        /// </summary>
        public static string global_cancel_change {
            get {
                return ResourceManager.GetString("global_cancel_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string global_city {
            get {
                return ResourceManager.GetString("global_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New Game.
        /// </summary>
        public static string global_create_new_game {
            get {
                return ResourceManager.GetString("global_create_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or Phone Number.
        /// </summary>
        public static string global_email_phone_number {
            get {
                return ResourceManager.GetString("global_email_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Request.
        /// </summary>
        public static string global_friend_request {
            get {
                return ResourceManager.GetString("global_friend_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string global_friends {
            get {
                return ResourceManager.GetString("global_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked out of the game.
        /// </summary>
        public static string global_game_expel {
            get {
                return ResourceManager.GetString("global_game_expel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick Player.
        /// </summary>
        public static string global_kick_player {
            get {
                return ResourceManager.GetString("global_kick_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string global_log_in {
            get {
                return ResourceManager.GetString("global_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string global_modify_password {
            get {
                return ResourceManager.GetString("global_modify_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string global_password {
            get {
                return ResourceManager.GetString("global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string global_ready {
            get {
                return ResourceManager.GetString("global_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string global_register {
            get {
                return ResourceManager.GetString("global_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register New User.
        /// </summary>
        public static string global_register_user {
            get {
                return ResourceManager.GetString("global_register_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Road.
        /// </summary>
        public static string global_road {
            get {
                return ResourceManager.GetString("global_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string global_start_game {
            get {
                return ResourceManager.GetString("global_start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Town.
        /// </summary>
        public static string global_town {
            get {
                return ResourceManager.GetString("global_town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string global_username {
            get {
                return ResourceManager.GetString("global_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote for kick.
        /// </summary>
        public static string global_vote_kick {
            get {
                return ResourceManager.GetString("global_vote_kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Profile Picture.
        /// </summary>
        public static string image_selector_title {
            get {
                return ResourceManager.GetString("image_selector_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access Code.
        /// </summary>
        public static string label_access_code {
            get {
                return ResourceManager.GetString("label_access_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha Nanofiber.
        /// </summary>
        public static string label_alpha_nanofibers {
            get {
                return ResourceManager.GetString("label_alpha_nanofibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigning turn….
        /// </summary>
        public static string label_assingning_turn {
            get {
                return ResourceManager.GetString("label_assingning_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build.
        /// </summary>
        public static string label_build {
            get {
                return ResourceManager.GetString("label_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CATAN SPACE.
        /// </summary>
        public static string label_catan_spacen {
            get {
                return ResourceManager.GetString("label_catan_spacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string label_chat {
            get {
                return ResourceManager.GetString("label_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string label_confirm_password {
            get {
                return ResourceManager.GetString("label_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connected.
        /// </summary>
        public static string label_connected {
            get {
                return ResourceManager.GetString("label_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already registered..
        /// </summary>
        public static string label_email_already_registered {
            get {
                return ResourceManager.GetString("label_email_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your code.
        /// </summary>
        public static string label_enter_code {
            get {
                return ResourceManager.GetString("label_enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the room code to join.
        /// </summary>
        public static string label_enter_lobby_code {
            get {
                return ResourceManager.GetString("label_enter_lobby_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter you new.
        /// </summary>
        public static string label_enter_new {
            get {
                return ResourceManager.GetString("label_enter_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your verification code.
        /// </summary>
        public static string label_enter_verification_code {
            get {
                return ResourceManager.GetString("label_enter_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epsilon Biomass.
        /// </summary>
        public static string label_epsilon_biomass {
            get {
                return ResourceManager.GetString("label_epsilon_biomass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string label_games_won {
            get {
                return ResourceManager.GetString("label_games_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You give.
        /// </summary>
        public static string label_give {
            get {
                return ResourceManager.GetString("label_give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has been kicked from the room..
        /// </summary>
        public static string label_has_been_kicked {
            get {
                return ResourceManager.GetString("label_has_been_kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please provide a valid email address..
        /// </summary>
        public static string label_invalid_email_message {
            get {
                return ResourceManager.GetString("label_invalid_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Joing Game....
        /// </summary>
        public static string label_joining_game {
            get {
                return ResourceManager.GetString("label_joining_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunar Stone.
        /// </summary>
        public static string label_lunar_stone {
            get {
                return ResourceManager.GetString("label_lunar_stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum number of players.
        /// </summary>
        public static string label_max_players {
            get {
                return ResourceManager.GetString("label_max_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message Field.
        /// </summary>
        public static string label_message_field {
            get {
                return ResourceManager.GetString("label_message_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Email.
        /// </summary>
        public static string label_new_email {
            get {
                return ResourceManager.GetString("label_new_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string label_new_password {
            get {
                return ResourceManager.GetString("label_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Phone Number.
        /// </summary>
        public static string label_new_phone_number {
            get {
                return ResourceManager.GetString("label_new_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Username.
        /// </summary>
        public static string label_new_username {
            get {
                return ResourceManager.GetString("label_new_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not ready.
        /// </summary>
        public static string label_no_ready {
            get {
                return ResourceManager.GetString("label_no_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        public static string label_phone {
            get {
                return ResourceManager.GetString("label_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string label_player {
            get {
                return ResourceManager.GetString("label_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join to the game.
        /// </summary>
        public static string label_player_join {
            get {
                return ResourceManager.GetString("label_player_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left the game.
        /// </summary>
        public static string label_player_left {
            get {
                return ResourceManager.GetString("label_player_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string label_points {
            get {
                return ResourceManager.GetString("label_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You receive.
        /// </summary>
        public static string label_receive {
            get {
                return ResourceManager.GetString("label_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string label_recover_password {
            get {
                return ResourceManager.GetString("label_recover_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email to recover your password.
        /// </summary>
        public static string label_recover_password_email {
            get {
                return ResourceManager.GetString("label_recover_password_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room:.
        /// </summary>
        public static string label_room {
            get {
                return ResourceManager.GetString("label_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the room.
        /// </summary>
        public static string label_room_name {
            get {
                return ResourceManager.GetString("label_room_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        public static string label_seconds {
            get {
                return ResourceManager.GetString("label_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting in.
        /// </summary>
        public static string label_starting {
            get {
                return ResourceManager.GetString("label_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player.
        /// </summary>
        public static string label_the_player {
            get {
                return ResourceManager.GetString("label_the_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time remaining: {0}.
        /// </summary>
        public static string label_time_remaining {
            get {
                return ResourceManager.GetString("label_time_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total points.
        /// </summary>
        public static string label_total_points {
            get {
                return ResourceManager.GetString("label_total_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trade offer.
        /// </summary>
        public static string label_trade_offer {
            get {
                return ResourceManager.GetString("label_trade_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in the required ACCOUNT fields.
        /// </summary>
        public static string label_user_required_fields {
            get {
                return ResourceManager.GetString("label_user_required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string label_username {
            get {
                return ResourceManager.GetString("label_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Votes.
        /// </summary>
        public static string label_votes {
            get {
                return ResourceManager.GetString("label_votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for players....
        /// </summary>
        public static string label_waiting_players {
            get {
                return ResourceManager.GetString("label_waiting_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekly.
        /// </summary>
        public static string label_weekly {
            get {
                return ResourceManager.GetString("label_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string label_winner {
            get {
                return ResourceManager.GetString("label_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a World.
        /// </summary>
        public static string label_world {
            get {
                return ResourceManager.GetString("label_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The application has ended.
        /// </summary>
        public static string log_info_end {
            get {
                return ResourceManager.GetString("log_info_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The application has started.
        /// </summary>
        public static string log_info_start {
            get {
                return ResourceManager.GetString("log_info_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game has started.
        /// </summary>
        public static string message_game_started {
            get {
                return ResourceManager.GetString("message_game_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has joined the room..
        /// </summary>
        public static string message_join_room {
            get {
                return ResourceManager.GetString("message_join_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad behavior.
        /// </summary>
        public static string option_bad_behavior {
            get {
                return ResourceManager.GetString("option_bad_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad conduct.
        /// </summary>
        public static string option_bad_conduct {
            get {
                return ResourceManager.GetString("option_bad_conduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exploits.
        /// </summary>
        public static string option_exploits {
            get {
                return ResourceManager.GetString("option_exploits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivity.
        /// </summary>
        public static string option_inactivity {
            get {
                return ResourceManager.GetString("option_inactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misuse of the game.
        /// </summary>
        public static string option_misuse_game {
            get {
                return ResourceManager.GetString("option_misuse_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offensive language.
        /// </summary>
        public static string option_offensive_language {
            get {
                return ResourceManager.GetString("option_offensive_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined.
        /// </summary>
        public static string option_undefined {
            get {
                return ResourceManager.GetString("option_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Includes upper, lower, nums, _ (8+).
        /// </summary>
        public static string password_prompt {
            get {
                return ResourceManager.GetString("password_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user is not verified, please verify.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart needed.
        /// </summary>
        public static string tittle_restart {
            get {
                return ResourceManager.GetString("tittle_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8-15 characters.
        /// </summary>
        public static string username_prompt {
            get {
                return ResourceManager.GetString("username:prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string window_edit_profile {
            get {
                return ResourceManager.GetString("window_edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick Player.
        /// </summary>
        public static string window_kick {
            get {
                return ResourceManager.GetString("window_kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        public static string window_main_menu {
            get {
                return ResourceManager.GetString("window_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover account.
        /// </summary>
        public static string window_recover_account {
            get {
                return ResourceManager.GetString("window_recover_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string windows_change_password {
            get {
                return ResourceManager.GetString("windows_change_password", resourceCulture);
            }
        }
    }
}
